#ifndef SYSTEM_OFW_VERIFY_H
#define SYSTEM_OFW_VERIFY_H

#include <stdint.h>
#include <stdbool.h>

/*
 * OFW integrity verification.
 *
 * The patch pipeline bakes a CRC-32 signature of each OFW backup image and its
 * paired external asset blob into src/common/ofw_crc.h (generated by
 * scripts/build/gen_ofw_crc.py). Here we re-compute those CRCs on the device
 * with the hardware CRC unit and compare, so the chainloader can refuse to copy
 * a recognized-but-corrupt/mismatched OFW into Bank 2 and boot it (STABILITY IS
 * LAW: never swap into an OFW we cannot boot). See DESIGN.md.
 */

/* CRC-32/MPEG-2 over a memory region via the STM32H7 hardware CRC unit (poly
 * 0x04C11DB7, init 0xFFFFFFFF, no reflection). `len` must be a multiple of 4.
 * `addr` may be memory-mapped external flash (read-only word access). */
uint32_t ofw_crc32(const void *addr, uint32_t len);

/* Verify the OFW backup at external-flash offset `spi_offset` AND its paired
 * asset blob against the baked signatures. Returns true only when BOTH match the
 * same baked record -- i.e. the backup is our patched build and the asset blob it
 * will reach for is the matching one, so it is safe to copy to Bank 2 and boot.
 * A spi_offset with no baked record, or a region that runs past the detected
 * flash, returns false (refuse). */
bool ofw_verify_by_spi(uint32_t spi_offset);

/* Verification status of a recognized external-flash region, for the Partition
 * Viewer. Maps the absolute address to a baked record (asset blob or OFW backup)
 * and CRCs the relevant window. NA = address is not a known OFW/asset region. */
typedef enum { OFW_VERIFY_NA, OFW_VERIFY_OK, OFW_VERIFY_BAD } ofw_verify_status_t;
ofw_verify_status_t ofw_verify_addr(uint32_t addr);

#endif /* SYSTEM_OFW_VERIFY_H */
