#ifndef UI_GUI_FONT_H
#define UI_GUI_FONT_H

#include <stdint.h>

/*
 * In-core Fusion Pixel 12px-monospaced ASCII font (printable 0x20-0x7E), the
 * always-present emergency-English fallback. Generated by
 * scripts/build/cook_font.py ascii from i18n/fonts/fusion-pixel-12px-monospaced-latin.otf
 * (OFL-1.1). DO NOT EDIT BY HAND.
 *
 * Each glyph is `w` columns wide (advance) by GUI_FONT_H rows; rows are 8-bit,
 * MSB-first (bit 0x80 = leftmost pixel). Row 0 sits at screen `y`; full-cell row
 * of row 0 is GUI_FONT_REF_TOP (so external blobs align by drawing at a y offset
 * relative to this same reference, whatever their own vertical band).
 */

#define GUI_FONT_FIRST    0x20u
#define GUI_FONT_LAST     0x7Eu
#define GUI_FONT_H        11u    /* rows stored per glyph */
#define GUI_FONT_REF_TOP  1u  /* full-12px-cell row that maps to draw-y */
#define GUI_FONT_MAX_W    6u

typedef struct {
    uint8_t w;                 /* advance width in pixels */
    uint8_t rows[GUI_FONT_H];  /* MSB-first, bit 0x80 = leftmost column */
} gui_glyph_t;

extern const gui_glyph_t gui_font_ascii[GUI_FONT_LAST - GUI_FONT_FIRST + 1];

#endif // UI_GUI_FONT_H
