#ifndef COMMON_OFW_CRC_H
#define COMMON_OFW_CRC_H

/*
 * GENERATED by scripts/build/gen_ofw_crc.py -- DO NOT EDIT BY HAND.
 * Regenerate after re-patching the OFW:  make patch && make ofw-crc
 *
 * Baked CRC-32/MPEG-2 signatures of each patched OFW backup image and its
 * paired external asset blob (save regions excluded). The chainloader
 * re-checks these on the device before copying an OFW into Bank 2 and
 * booting it, refusing a recognized-but-mismatched image. See
 * src/chainloader/system/ofw_verify.c and DESIGN.md.
 */

#include <stdint.h>

typedef struct {
    uint32_t spi_offset;      /* extflash offset of the 128 KiB OFW backup (selector key) */
    uint32_t internal_len;    /* bytes of the backup image to CRC */
    uint32_t internal_crc;    /* expected CRC of the backup image */
    uint32_t asset_offset;    /* extflash offset of the asset-blob base */
    uint32_t asset_win_start; /* static-window start within the blob (save holes excluded) */
    uint32_t asset_win_len;   /* static-window length */
    uint32_t asset_crc;       /* expected CRC of the static asset window */
} ofw_crc_record_t;

#define OFW_CRC_RECORD_COUNT 2
static const ofw_crc_record_t OFW_CRC_RECORDS[OFW_CRC_RECORD_COUNT] = {
    { /* mario */ 0x00520000, 0x00020000, 0x74C0EB8E, 0x00400000, 0x00000000, 0x000D9000, 0xCB9F6FF6 },
    { /* zelda */ 0x00500000, 0x00020000, 0x78535756, 0x00000000, 0x00020000, 0x003054A0, 0x62675FBF },
};

#endif /* COMMON_OFW_CRC_H */
