#ifndef COMMON_RETROGO_CRC_H
#define COMMON_RETROGO_CRC_H

/*
 * GENERATED by scripts/build/gen_retrogo_crc.py -- DO NOT EDIT BY HAND.
 * Regenerate after rebuilding Retro-Go:  make build-rg-sd && make retrogo-crc
 *
 * Baked CRC-32/MPEG-2 of the Retro-Go internal-flash image (the bytes flashed at
 * RETROGO_BASE). The chainloader re-checks it on the device before launching
 * Retro-Go and falls back to its own menu on a mismatch (partial/corrupt flash).
 * See src/chainloader/system/ofw_verify.c (retrogo_crc_ok) and DESIGN.md.
 *
 * RETROGO_CRC_LEN == 0 means "not baked": the device gate fails OPEN (boots
 * Retro-Go) so a tree without a regenerated header is never bricked.
 */

#include <stdint.h>

#define RETROGO_CRC_LEN  0x00035B80u   /* bytes of the payload to CRC */
#define RETROGO_CRC      0x170C4408u

#endif /* COMMON_RETROGO_CRC_H */
